// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPaIlqfuz_lywnhsCKCcbMRkunwg6HIhk',
    appId: '1:741074974346:web:3574248aaa4281ca989f73',
    messagingSenderId: '741074974346',
    projectId: 't-store-live',
    authDomain: 't-store-live.firebaseapp.com',
    storageBucket: 't-store-live.firebasestorage.app',
    measurementId: 'G-13JG9X1C5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrQdmLxyweZJxIuR541ekGOHbqfw-azBY',
    appId: '1:741074974346:android:5bf0c406ed44c3c2989f73',
    messagingSenderId: '741074974346',
    projectId: 't-store-live',
    storageBucket: 't-store-live.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHmttz_6_5IP7WeL7QtiIWIJPX_y8u9oY',
    appId: '1:741074974346:ios:5a64089b6f010ab3989f73',
    messagingSenderId: '741074974346',
    projectId: 't-store-live',
    storageBucket: 't-store-live.firebasestorage.app',
    androidClientId: '741074974346-k9vrnpnhoo6hqkfj1kmmvvlcuhc90j6i.apps.googleusercontent.com',
    iosClientId: '741074974346-kc8j4k0p7ib95p2m8uj7gmv5ichi9or0.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );
}
